/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
//import UI.Declare_path.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author WhysoseriousONI
 */
public class PayForStud extends javax.swing.JFrame {

    /**
     * Creates new form ViewPay
     */
    String global, balrem;
    public PayForStud() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rno = new javax.swing.JTextField();
        classsel = new javax.swing.JComboBox<>();
        secsel = new javax.swing.JComboBox<>();
        termsel = new javax.swing.JComboBox<>();
        datesel = new com.toedter.calendar.JDateChooser();
        pay = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rem = new javax.swing.JLabel();
        tot = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        erro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Roll Number");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Class");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Section");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Select Term");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Select Today's Date");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Remaining to pay");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Amount paying now");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Total Fee");

        rno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        classsel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        classsel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose standard", "I STD", "II STD", "III STD", "IV  STD", "V STD", "VI STD", "VII STD", "VIII STD", "IX STD", "X STD", "XI STD" }));

        secsel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        secsel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A" }));

        termsel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        termsel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose term", "Term 1", "Term 2", "Term 3" }));

        pay.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pay.setText("0");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        pay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                payKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                payKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel9.setText("Payment Page");

        rem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rem.setText("0");

        tot.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tot.setText("0");

        jButton3.setText("Generate Record");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Calculate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        erro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        erro.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jButton2)))
                .addContainerGap(327, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(erro)
                        .addComponent(jLabel6)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rno, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secsel, 0, 341, Short.MAX_VALUE)
                            .addComponent(classsel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(termsel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rem, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tot)
                            .addComponent(datesel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(3, 3, 3)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(classsel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(secsel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(termsel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton3)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(datesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(erro)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UI.mainpage mp = new mainpage();
        mp.setVisible(true);
        dispose();// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// submit
        try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");//necessary
                String dbURL = Declare_path.DBU_STRING;//openning DB
                Connection connection = DriverManager.getConnection(dbURL);//estasblis
                String sql = "";
                String cls = classsel.getSelectedItem().toString();
                String scs = secsel.getSelectedItem().toString();
                String roll = rno.getText() + cls + scs;
                String trm = termsel.getSelectedItem().toString();
                
                if (trm.equals("Term 1")) {
                    sql = "Update paystatus set term1=?,term1date=?,term1amt=?,due=?,done='NO' where rollno=?";
                }
                if (trm.equals("Term 2")) {
                    sql = "update paystatus set term2=?,term2date=?,term2amt=?,due=?,done='NO' where rollno=?";
                }
                if (trm.equals("Term 3")) {
                    sql = "update  paystatus set term3=?,term3date=?,term3amt=? ,due=?,done='YES' where rollno=?";
                }
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(datesel.getDate());

                PreparedStatement preparedStatement = connection.prepareStatement(sql);//put query to MSaccess
                preparedStatement.setString(1, "paid");
                preparedStatement.setString(2, date);
                preparedStatement.setString(3, pay.getText());
                preparedStatement.setString(4, rem.getText());
                preparedStatement.setString(5, roll);
                preparedStatement.executeUpdate();
                if (trm.equals("Term 2") || trm.equals("Term 1")) {
                    dispose();
                    UI.NextPay np = new NextPay();
                    np.rno.setText(rno.getText());
                    np.clss.setText(cls);
                    np.sec.setText(scs);
                    np.setVisible(true);
                }
                
            /*
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");//necessary
            String dbURL = Declare_path.DBU_STRING;//openning DB
            Connection connection = DriverManager.getConnection(dbURL);//estasblis
            String sql = "";
            String cls = classsel.getSelectedItem().toString();
            String scs = secsel.getSelectedItem().toString();
            String roll = rno.getText() + cls + scs;
            String trm = termsel.getSelectedItem().toString();
            if (trm.equals("Term 1")) {
                sql = "insert into paystatus (rollno, class, sec,term1,term1date,term1amt, due) values(?,?,?,?,?,?,?)";
            }
            if (trm.equals("Term 2")) {
                sql = "insert into paystatus (rollno, class, sec,term2,term2date,term2amt,due) values(?,?,?,?,?,?,?)";
            }
            if (trm.equals("Term 3")) {
                sql = "insert into paystatus (rollno, class, sec,term3,term3date,term3amt,due)values(?,?,?,?,?,?,?)";
            }
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(datesel.getDate());

            PreparedStatement preparedStatement = connection.prepareStatement(sql);//put query to MSaccess
            preparedStatement.setString(1, roll);
            preparedStatement.setString(2, cls);
            preparedStatement.setString(3, scs);
            preparedStatement.setString(4, "paid");
            preparedStatement.setString(5, date);
            preparedStatement.setString(6, pay.getText());
            preparedStatement.setString(7, rem.getText());//global
//            preparedStatement.setString(8, rem.getText());
//            preparedStatement.setString(9, );
            preparedStatement.executeUpdate();
*/
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
           /* try {
                //update
                System.out.println("");

            } catch (SQLException ex1) {System.out.println("error from ex");
            } catch (ClassNotFoundException ex1) {
            }*/
            System.err.println("exception by sql");
            Logger.getLogger(PayForStud.class.getName()).log(Level.SEVERE, null, ex);
        }
//        finally{
//            String trm = termsel.getSelectedItem().toString();
//            
//        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection conn = DriverManager.getConnection(Declare_path.DBU_STRING);
            String roll = rno.getText().toString() + classsel.getSelectedItem().toString() + secsel.getSelectedItem().toString();
            String sql = "Select * from paystatus where rollno=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, roll);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                erro.setText("");
                global = rs.getString("due");
                rem.setText(global);
                tot.setText(rs.getString("total_fee"));
            } else {
                erro.setText("no data found");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PayForStud.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PayForStud.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int p = Integer.parseInt(pay.getText());
        int r = Integer.parseInt(global);
        String res = Integer.toString(r - p);
        rem.setText(res);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void payKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payKeyPressed

      // TODO add your handling code here:
    }//GEN-LAST:event_payKeyPressed

    private void payKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payKeyTyped
    // TODO add your handling code here:
    }//GEN-LAST:event_payKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayForStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayForStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayForStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayForStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayForStud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> classsel;
    private com.toedter.calendar.JDateChooser datesel;
    private javax.swing.JLabel erro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pay;
    private javax.swing.JLabel rem;
    private javax.swing.JTextField rno;
    private javax.swing.JComboBox<String> secsel;
    private javax.swing.JComboBox<String> termsel;
    private javax.swing.JLabel tot;
    // End of variables declaration//GEN-END:variables
}
